#pragma once

enum ADVANCED_CHAT_LOCAL_CONSTANT
{
	ADVANCED_CHAT_REAL_NAME_LENGTH = 20,
	ADVANCED_CHAT_NICKNAME_LENGTH = 20,
	ADVANCED_CHAT_PLAYER_KEY_LENGTH = 64,

	ADVANCED_CHAT_SECTOR_WIDTH = 50,
	ADVANCED_CHAT_SECTOR_HEIGHT = 50,

	ADVANCED_CHAT_MAXIMUM_MESSAGE_LENGTH = 1024,
};

enum ADVANCED_CHAT_CLIENT_REQUEST_INDEX
{
	ADVANCED_CHAT_CLIENT_REQUEST_LOGIN = 1,
	ADVANCED_CHAT_CLIENT_REQUEST_SECTOR_MOVE = 3,
	ADVANCED_CHAT_CLIENT_REQUEST_MESSAGE = 5,
	ADVANCED_CHAT_CLIENT_REQUEST_HEARTBEAT = 7,
	//ADVANCED_CHAT_CLIENT_REQUEST_ALIVE_SIGNAL = 7,
	
	ADVANCED_CHAT_CLIENT_REQUST_COUNT = 4
};

enum ADVANCED_LOGIN_SERVER_REQUEST_INDEX
{
	ADVANCED_LOGIN_SERVER_REQUEST_LINK = 10001,
	ADVANCED_LOGIN_SERVER_REQUEST_LOGIN_CONFIRM = 10002,

	ADVANCED_LOGIN_SERVER_REQUEST_COUNT = 2
};

enum ADVANCED_CHAT_SERVER_RESPONSE_INDEX
{
	ADVANCED_CHAT_SERVER_RESPONSE_LOGIN = 2,
	ADVANCED_CHAT_SERVER_RESPONSE_SECTOR_MOVE = 4,
	ADVANCED_CHAT_SERVER_RESPONSE_MESSAGE = 6,
	ADVANCED_CHAT_SERVER_RESPONSE_HEARTBEAT = 8,
	//ADVANCED_CHAT_SERVER_RESPONSE_ALIVE_SIGNAL = 8,

	ADVANCED_CHAT_SERVER_RESPONSE_LINK = 10001,
	ADVANCED_CHAT_SERVER_RESPONSE_LOGIN_CONFIRM = 10003,

	ADVANCED_CHAT_SERVER_RESPONSE_COUNT
};

enum ADVANCED_CHAT_SERVER_LOGIN_STATUS_INDEX
{
	ADVANCED_CHAT_SERVER_LOGIN_STATUS_NONE = -1,
	ADVANCED_CHAT_SERVER_LOGIN_STATUS_FAILURE,
	ADVANCED_CHAT_SERVER_LOGIN_STATUS_SUCCESS,
	ADVANCED_CHAT_SERVER_LOGIN_STATUS_GAME,
	ADVANCED_CHAT_SERVER_LOGIN_STATUS_NO_ACCOUNT,
	ADVANCED_CHAT_SERVER_LOGIN_STATUS_NO_SESSION,
	ADVANCED_CHAT_SERVER_LOGIN_STATUS_NO_STATUS,
	ADVANCED_CHAT_SERVER_LOGIN_STATUS_NO_SERVER,

	ADVANCED_CHAT_SERVER_LOGIN_STATUS_COUNT = 8,
};

struct AdvancedChatClientServer
{
	UINT64 SessionKey;

	DWORD PreviousHeartbeatTime;

	SRWLOCK Lock;
};

struct AdvancedChatClientPlayer
{
	UINT64 SessionKey; //SessionID
	
	UINT64 AccountKey; //AccountNo
	WCHAR RealName[ADVANCED_CHAT_REAL_NAME_LENGTH];
	WCHAR Nickname[ADVANCED_CHAT_NICKNAME_LENGTH];
	CHAR PlayerKey[ADVANCED_CHAT_PLAYER_KEY_LENGTH];

	UINT SectorIndexX;
	UINT SectorIndexY;

	UINT MessageSize;
	WCHAR Message[ADVANCED_CHAT_MAXIMUM_MESSAGE_LENGTH];

	DWORD PreviousHeartbeatTime;

	SRWLOCK Lock;
};

struct AdvancedChatWork
{
	UINT64 SessionKey;
	SerialPacketQueue<IOCP_PacketHeader>* PacketSPQ_Address;
};

struct AdvancedChatSector
{
	list<AdvancedChatClientPlayer*> CPAL; //AdvancedChatClientPlayerAddressL CPAL;

	SRWLOCK Lock;
};

typedef list<AdvancedChatClientServer> AdvancedChatClientServerL;
typedef list<AdvancedChatClientServer>::iterator AdvancedChatClientServerLI;

typedef list<AdvancedChatClientServer*> AdvancedChatClientServerAddressL;
typedef list<AdvancedChatClientServer*>::iterator AdvancedChatClientServerAddressLI;

typedef list<AdvancedChatClientPlayer> AdvancedChatClientPlayerL;
typedef list<AdvancedChatClientPlayer>::iterator AdvancedChatClientPlayerLI;

typedef list<AdvancedChatClientPlayer*> AdvancedChatClientPlayerAddressL;
typedef list<AdvancedChatClientPlayer*>::iterator AdvancedChatClientPlayerAddressLI;